manifest:
  defaults:
    revision: main
  
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: cantruchd
      url-base: https://github.com/cantruchd 

  projects:
    - name: zmk
      remote: cantruchd
      import: app/west.yml
      revision: mainfromzmk
    - name: nice_view_gem
      remote: cantruchd
      revision: main

  self:
    path: config
