manifest:
  defaults:
    revision: v0.3
  remotes:
    #- name: zmkfirmware
     # url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: cantruchd #new entry
      url-base: https://github.com/cantruchd #new entry
    # - name: pbogut #new entry
    #   url-base: https://github.com/pbogut #new entry
  projects:
    - name: zmk
      #remote: zmkfirmware
      remote: cantruchd
      import: app/west.yml
      revision: mainfromzmk #new entry
      # 2. KHAI BÁO MODULE WIDGET CUSTOM BẰNG URL CỤC BỘ (LƯU Ý: file://...)
    # Cách này giúp West thỏa mãn yêu cầu về URL/remote mà không cần remote ngoài
    - name: nice_view_custom_widgets
      remote: local              # Gán cho remote 'local'
      path: app/nice_view_custom_widgets 
      # BỎ revision, url (West sẽ không cố gắng clone/fetch)
      #
  self:
    path: config
