manifest:
  defaults:
    revision: v0.3
  remotes:
    #- name: zmkfirmware
     # url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
    - name: cantruchd #new entry
      url-base: https://github.com/cantruchd #new entry
  projects:
    - name: zmk
      #remote: zmkfirmware
      remote: cantruchd
      import: app/west.yml
    # - name: nice-view-gem #new entry
    #   remote: cantruchd #new entry
    #   revision: main #new entry
  self:
    path: config
